apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-vue
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-vue
  template:
    metadata:
      labels:
        app: frontend-vue
    spec:
      containers:
        - name: frontend-vue
          image: localhost:32000/frontend-vue:v4
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-vue
  namespace: apps
spec:
  type: ClusterIP
  selector:
    app: frontend-vue
  ports:
    - port: 80
      targetPort: 80
